### ISSUE TITLE
Report progress to pacman

### ISSUE THREAD

**Issue by wallace11** [anatol/pacoloco#5]
In case a download takes more than a couple of seconds, since nothing is reported by pacoloco, it's being interpreted as a timeout.

Consider the following config:
```yaml
ck:
    url: http://repo-ck.com/
```

Trying to run `pacman -S linux-ck` would result in an error:
```
error: failed retrieving file 'linux-ck-5.5.5-1-x86_64.pkg.tar.zst' from server:port : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
```

Cheers.

**Comment by anatol** [comment]
It comes from the fact that `pacoloco` downloads the file first and only then starts serving it to the client. The code is located here https://github.com/anatol/pacoloco/blob/master/pacoloco.go#L102

As downloading requires some time the client need to wait. And it is where the timeout you see comes from.

pacoloco needs to be able download the file, save it to disk and send to the client at the same time.

**Comment by wallace11** [comment]
You can check out another go project which I'm currently using, called pkgproxy.
I haven't gone over the code, but from quick skimming it looks like the whole magic is done in the following function: https://github.com/buckket/pkgproxy/blob/master/pkgproxy.go#L107

Hope this information would be helpful to improve this already wonderful tool ;)

**Comment by anatol** [comment]
`pkgproxy`  implements 'copy data to two writers' manually using `for { Copy }` loop. I was hoping for some off the shelf solution. And indeed there is `io.MultiWriter` functionality that does the same.

I just pushed a commit that implements this feature. Could you please download https://github.com/anatol/pacoloco/tree/concurrent-download branch and verify that it works for you as expected?

**Comment by wallace11** [comment]
Sounds good.
I'll check it out this weekend.

**Comment by wallace11** [comment]
Okay,  
I installed the new branch and while it hasn't timeouted on me with the official repos, it felt less "snappy" compared to pkgproxy. I'll have to conduct more through tests in order to confirm that it's not my subjective feeling.

However, the problem with repo-ck remains, and I still get "operation too slow" error...  
Have you tried adding this repo and installing `linux-ck` package for instance? It should give you a pretty good estimation to how well your solution works...

**Comment by anatol** [comment]
> it felt less "snappy" compared to pkgproxy. I'll have to conduct more through tests

It would be great to quantify this statement. I briefly looked at `pkgproxy` and it uses pretty much the same download/caching logic (except `pkgproxy` does one more HEAD request for `.db` files). So I will be mildly surprised if there is a big difference in throughput/latency numbers between these 2 projects.

**Comment by anatol** [comment]
An unrelated note but you might be interested to check that as well.

There is a WIP branch that aims to add parallel download to pacman. It will be super useful for servers with a large latency or in case when different servers have different network bandwidth. I suggest to check it as well https://github.com/anatol/pacman/tree/parallel-download https://www.reddit.com/r/archlinux/comments/f5xr9s/pacoloco_caching_proxy_for_arch_linux_repo/

**Comment by anatol** [comment]
Another difference between these two tools is the way how they handle caching for `.db.sig` files. `pacoloco` treats it (and `.files`) as modifiable files and thus it re-checks its modification date at the remote mirror every time.

I briefly checked `pkgproxy` sources and it seams re-fetches `.db` files only. All other files are cached forever and served locally from the disk.

**Comment by wallace11** [comment]
Please tell me how I can help you testing it, as I've never really looked too deep into how pacman fetches files...
While my statement of how snappy it "feels" is subjective, as I said, timing out on slow mirrors is probably an issue that needs to be looked into.

**Comment by anatol** [comment]
> However, the problem with repo-ck remains, and I still get "operation too slow" error...

To clarify do you see pacman failing with "operation too slow"? It should really be fixed with the changes above (assuming that repo-ck.com does not timeout).

Or maybe you see no output from pacman and then the package quickly marked as completed. If this one then it happens because `http://repo-ck.com` returns compressed output without `Content-Length` set and it confuses pacman progressbar.

**Comment by anatol** [comment]
> Please tell me how I can help you testing it, as I've never really looked too deep into how pacman fetches files...

To stop fetching signatures you can edit `/etc/pacman.conf` and set `SigLevel = Never` for the database.

**Comment by anatol** [comment]
I pushed the download-and-serve feature to `master`. This should fix `operation too slow` pacman behavior. Please reopen this ticket if you still see the issue.

**Comment by wallace11** [comment]
Quick update:
I tested the latest change on a couple of my machines at the same time and everything seems to be working flawlessly (no need to change siglevel).
Thank you for your hard work!

**Comment by anatol** [comment]
Great, thank you for the confirmation!
